
version: 2

models:
  - name: quarter_HiredEmployees
    description: "Model to show how much employees the company had hired in the 4 quarters of a year"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

