# Generated by Django 4.2.3 on 2023-07-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hired_employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("datetime", models.DateField()),
                ("department_id", models.CharField(max_length=3)),
                ("job_id", models.CharField(max_length=3)),
            ],
        ),
    ]
